apiVersion: v1
data:
  secretkey: eDU5U2hKQWlvTndkTmJKa3o4VFBNbmJTbFBZS2tBeWpycnFTcjQ1VExhaXJFOHQwQXlrWXBpTzlYOW43RVE3VAp5NTVXVDNDRkl2ZExERkFISmZTWmN0NzVWWFFwL3ZZc2xEUEU3b21ZOFVleEl6NmpqU05tcXArZ3ZQWVdrazEwCkdEUjZPSmNzUWJzZlowRkFSUFhWZllGU21FNHpsTlloRkQ0SFJuSTE3dHM9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
