apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://192.168.254.100
  dex.config: |
    connectors:
    - config:
        clientID: {{ dex.client_id | default('') }}
        clientSecret: {{ dex.client_secret | default('') }}
        orgs:
        - name: {{ dex.gh_org_name | default('none') }}
        redirectURI: https://192.168.254.100/api/dex/callback
      id: github
      name: GitHub
      type: github

